// // File: src/app/(shop)/layout.js
// // Sirf shop pages ke liye green header with cart

// export default function ShopLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <div>
//       <header style={{ 
//         background: 'green', 
//         color: 'white', 
//         padding: '20px',
//         display: 'flex',
//         justifyContent: 'space-between'
//       }}>
//         <h2>🛒 Online Store</h2>
//         <span>Cart (3 items)</span>
//       </header>
//       {children}
//     </div>
//   );
// }















import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";
// import Navbar from "./component/Navbar";
// import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="min-h-screen flex-1 flex flex-col">
        {children}
      </main>
      <Footer />
    </>
  );
}
