// // File: src/app/(marketing)/layout.js
// // Sirf marketing pages ke liye blue header

// export default function MarketingLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <div>
//       <header style={{ 
//         background: 'blue', 
//         color: 'white', 
//         padding: '20px' 
//       }}>
//         <h2>🏠 Marketing Website</h2>
//       </header>
//       {children}
//     </div>
//   );
// }












import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";
// import Navbar from "./component/Navbar";
// import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <main className="min-h-screen flex-1 flex flex-col">
        {children}
      </main>
      <Footer />
    </>
  );
}
