// File: src/app/(auth)/layout.js
// Simple centered layout for login/register

// export default function AuthLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <div style={{ 
//       display: 'flex', 
//       justifyContent: 'center', 
//       alignItems: 'center',
//       minHeight: '100vh',
//       background: 'linear-gradient(to right, #667eea, #764ba2)'
//     }}>
//       <div style={{ 
//         background: 'white', 
//         padding: '40px', 
//         borderRadius: '10px',
//         boxShadow: '0 10px 25px rgba(0,0,0,0.2)'
//       }}>
//         {children}
//       </div>
//     </div>
//   );
// }








import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Navbar from "../component/Navbar";
import Footer from "../component/Footer";
// import Navbar from "./component/Navbar";
// import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen flex-1 flex flex-col">
      {children}
    </main>
  );
}
